### ISSUE TITLE
Remove icons and replace them with Unicode chars

### ISSUE THREAD

**Issue by Marocco2** [tmeedend/camtool#2]
https://www.racedepartment.com/threads/camtool-2.134902/page-5#post-2907832

- Less disk intensive
- Less AC calls in Update() which could bring more performance

**Comment by tmeedend** [comment]
I'm not sure we can replace them by characters. Which ones?

The real problem was that the app was constantly redrawing itself. I have fixed most of the redraw calls, so this is not an issue anymore.

There one exception for disabled buttons which get redrawn but we cannot avoid it as depending of the frame selected, the button need to be redrawn. But I have already lowered these kind of draws so they are not done at each frame.

But there is still one thing I can do to optimize a bit: compare the last background img used, and if it's the same, don't change it. I'll do it :)

**Comment by tmeedend** [comment]
fixed
